### ISSUE TITLE
ラベルのテキストをプログラムから変更

### ISSUE THREAD

**Issue by ryotaman** [nkatou01/swift-test#3]
FirstViewControllerのUILabelをFristViewController.swiftから変更する
IBOutlet 宣言を利用して プログラム内から内容を上書きして下さい

実装が出来たらPUSH後にコメントして下さい。

**Comment by nkatou01** [comment]
実装してCommit/Pushしました。

**Comment by ryotaman** [comment]
変更確認出来ました :+1:
