### ISSUE TITLE
TextFieldの配置

### ISSUE THREAD

**Issue by ryotaman** [nkatou01/swift-test#4]
StoryBordのFirstViewController 内にTextFieldを配置し、
常に中央になるようオートレイアウトを設定
- TextFieldの表示サイズを変更
- 高さを変更

実装が出来たらPUSH後にコメントして下さい。

**Comment by nkatou01** [comment]
実装してCommit/Pushしました。

**Comment by ryotaman** [comment]
実装確認出来ました :+1:
