### ISSUE TITLE
TextFieldのキーボード閉じ

### ISSUE THREAD

**Issue by ryotaman** [nkatou01/swift-test#6]
TextFieldをタップ時に出現するキーボードを
完了ボタン（確定、done等）がタップされた時にキーボードをしまう

実装が出来たらPUSH後にコメントして下さい。

**Comment by nkatou01** [comment]
実装してCommit/Pushしました。

**Comment by ryotaman** [comment]
キーボードが閉じられること確認出来ました :+1:
